# Generated by Django 4.2.4 on 2023-09-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar_2_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField(max_length=1000)),
                ('bd', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='gamemodel',
            options={'ordering': ['-played']},
        ),
    ]
