# Generated by Django 4.2.4 on 2023-09-02 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seminar_2_app', '0003_category_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('change_date', models.DateField(default=models.DateField(auto_now_add=True))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminar_2_app.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminar_2_app.post')),
            ],
        ),
    ]
