# Generated by Django 4.2.4 on 2023-09-05 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar_2_app', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='change_date',
            field=models.DateField(default=datetime.date(2023, 9, 5)),
        ),
    ]
